/*
 * Copyright (c) 2015-2018, Cloudera, Inc. All Rights Reserved.
 *
 * Cloudera, Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"). You may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * This software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for
 * the specific language governing permissions and limitations under the
 * License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_multiple_message.proto

package com.cloudera.labs.envelope.input.translate;

public final class ProtobufMultipleMessage {
  private ProtobufMultipleMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OtherExampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cloudera.labs.envelope.input.translate.OtherExample)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string other = 1;</code>
     */
    java.lang.String getOther();
    /**
     * <code>string other = 1;</code>
     */
    com.google.protobuf.ByteString
        getOtherBytes();
  }
  /**
   * Protobuf type {@code com.cloudera.labs.envelope.input.translate.OtherExample}
   */
  public  static final class OtherExample extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.cloudera.labs.envelope.input.translate.OtherExample)
      OtherExampleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OtherExample.newBuilder() to construct.
    private OtherExample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OtherExample() {
      other_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OtherExample(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              other_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.internal_static_com_cloudera_labs_envelope_input_translate_OtherExample_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.internal_static_com_cloudera_labs_envelope_input_translate_OtherExample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample.class, com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample.Builder.class);
    }

    public static final int OTHER_FIELD_NUMBER = 1;
    private volatile java.lang.Object other_;
    /**
     * <code>string other = 1;</code>
     */
    public java.lang.String getOther() {
      java.lang.Object ref = other_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        other_ = s;
        return s;
      }
    }
    /**
     * <code>string other = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOtherBytes() {
      java.lang.Object ref = other_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        other_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOtherBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, other_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOtherBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, other_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample)) {
        return super.equals(obj);
      }
      com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample other = (com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample) obj;

      boolean result = true;
      result = result && getOther()
          .equals(other.getOther());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OTHER_FIELD_NUMBER;
      hash = (53 * hash) + getOther().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.cloudera.labs.envelope.input.translate.OtherExample}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cloudera.labs.envelope.input.translate.OtherExample)
        com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.internal_static_com_cloudera_labs_envelope_input_translate_OtherExample_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.internal_static_com_cloudera_labs_envelope_input_translate_OtherExample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample.class, com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample.Builder.class);
      }

      // Construct using com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        other_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.internal_static_com_cloudera_labs_envelope_input_translate_OtherExample_descriptor;
      }

      @java.lang.Override
      public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample getDefaultInstanceForType() {
        return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample.getDefaultInstance();
      }

      @java.lang.Override
      public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample build() {
        com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample buildPartial() {
        com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample result = new com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample(this);
        result.other_ = other_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample) {
          return mergeFrom((com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample other) {
        if (other == com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample.getDefaultInstance()) return this;
        if (!other.getOther().isEmpty()) {
          other_ = other.other_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object other_ = "";
      /**
       * <code>string other = 1;</code>
       */
      public java.lang.String getOther() {
        java.lang.Object ref = other_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          other_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string other = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOtherBytes() {
        java.lang.Object ref = other_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          other_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string other = 1;</code>
       */
      public Builder setOther(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        other_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string other = 1;</code>
       */
      public Builder clearOther() {
        
        other_ = getDefaultInstance().getOther();
        onChanged();
        return this;
      }
      /**
       * <code>string other = 1;</code>
       */
      public Builder setOtherBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        other_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.cloudera.labs.envelope.input.translate.OtherExample)
    }

    // @@protoc_insertion_point(class_scope:com.cloudera.labs.envelope.input.translate.OtherExample)
    private static final com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample();
    }

    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OtherExample>
        PARSER = new com.google.protobuf.AbstractParser<OtherExample>() {
      @java.lang.Override
      public OtherExample parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OtherExample(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OtherExample> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OtherExample> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.OtherExample getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IncludedExampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cloudera.labs.envelope.input.translate.IncludedExample)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string included = 1;</code>
     */
    java.lang.String getIncluded();
    /**
     * <code>string included = 1;</code>
     */
    com.google.protobuf.ByteString
        getIncludedBytes();
  }
  /**
   * Protobuf type {@code com.cloudera.labs.envelope.input.translate.IncludedExample}
   */
  public  static final class IncludedExample extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.cloudera.labs.envelope.input.translate.IncludedExample)
      IncludedExampleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IncludedExample.newBuilder() to construct.
    private IncludedExample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IncludedExample() {
      included_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IncludedExample(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              included_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.internal_static_com_cloudera_labs_envelope_input_translate_IncludedExample_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.internal_static_com_cloudera_labs_envelope_input_translate_IncludedExample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.class, com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.Builder.class);
    }

    public static final int INCLUDED_FIELD_NUMBER = 1;
    private volatile java.lang.Object included_;
    /**
     * <code>string included = 1;</code>
     */
    public java.lang.String getIncluded() {
      java.lang.Object ref = included_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        included_ = s;
        return s;
      }
    }
    /**
     * <code>string included = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIncludedBytes() {
      java.lang.Object ref = included_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        included_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIncludedBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, included_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIncludedBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, included_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample)) {
        return super.equals(obj);
      }
      com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample other = (com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample) obj;

      boolean result = true;
      result = result && getIncluded()
          .equals(other.getIncluded());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INCLUDED_FIELD_NUMBER;
      hash = (53 * hash) + getIncluded().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.cloudera.labs.envelope.input.translate.IncludedExample}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cloudera.labs.envelope.input.translate.IncludedExample)
        com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.internal_static_com_cloudera_labs_envelope_input_translate_IncludedExample_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.internal_static_com_cloudera_labs_envelope_input_translate_IncludedExample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.class, com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.Builder.class);
      }

      // Construct using com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        included_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.internal_static_com_cloudera_labs_envelope_input_translate_IncludedExample_descriptor;
      }

      @java.lang.Override
      public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample getDefaultInstanceForType() {
        return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.getDefaultInstance();
      }

      @java.lang.Override
      public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample build() {
        com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample buildPartial() {
        com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample result = new com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample(this);
        result.included_ = included_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample) {
          return mergeFrom((com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample other) {
        if (other == com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.getDefaultInstance()) return this;
        if (!other.getIncluded().isEmpty()) {
          included_ = other.included_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object included_ = "";
      /**
       * <code>string included = 1;</code>
       */
      public java.lang.String getIncluded() {
        java.lang.Object ref = included_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          included_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string included = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIncludedBytes() {
        java.lang.Object ref = included_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          included_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string included = 1;</code>
       */
      public Builder setIncluded(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        included_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string included = 1;</code>
       */
      public Builder clearIncluded() {
        
        included_ = getDefaultInstance().getIncluded();
        onChanged();
        return this;
      }
      /**
       * <code>string included = 1;</code>
       */
      public Builder setIncludedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        included_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.cloudera.labs.envelope.input.translate.IncludedExample)
    }

    // @@protoc_insertion_point(class_scope:com.cloudera.labs.envelope.input.translate.IncludedExample)
    private static final com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample();
    }

    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IncludedExample>
        PARSER = new com.google.protobuf.AbstractParser<IncludedExample>() {
      @java.lang.Override
      public IncludedExample parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IncludedExample(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IncludedExample> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IncludedExample> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MultipleExampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cloudera.labs.envelope.input.translate.MultipleExample)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.cloudera.labs.envelope.input.translate.IncludedExample included_example = 1;</code>
     */
    boolean hasIncludedExample();
    /**
     * <code>.com.cloudera.labs.envelope.input.translate.IncludedExample included_example = 1;</code>
     */
    com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample getIncludedExample();
    /**
     * <code>.com.cloudera.labs.envelope.input.translate.IncludedExample included_example = 1;</code>
     */
    com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExampleOrBuilder getIncludedExampleOrBuilder();
  }
  /**
   * Protobuf type {@code com.cloudera.labs.envelope.input.translate.MultipleExample}
   */
  public  static final class MultipleExample extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.cloudera.labs.envelope.input.translate.MultipleExample)
      MultipleExampleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MultipleExample.newBuilder() to construct.
    private MultipleExample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultipleExample() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MultipleExample(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.Builder subBuilder = null;
              if (includedExample_ != null) {
                subBuilder = includedExample_.toBuilder();
              }
              includedExample_ = input.readMessage(com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(includedExample_);
                includedExample_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.internal_static_com_cloudera_labs_envelope_input_translate_MultipleExample_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.internal_static_com_cloudera_labs_envelope_input_translate_MultipleExample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample.class, com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample.Builder.class);
    }

    public static final int INCLUDED_EXAMPLE_FIELD_NUMBER = 1;
    private com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample includedExample_;
    /**
     * <code>.com.cloudera.labs.envelope.input.translate.IncludedExample included_example = 1;</code>
     */
    public boolean hasIncludedExample() {
      return includedExample_ != null;
    }
    /**
     * <code>.com.cloudera.labs.envelope.input.translate.IncludedExample included_example = 1;</code>
     */
    public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample getIncludedExample() {
      return includedExample_ == null ? com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.getDefaultInstance() : includedExample_;
    }
    /**
     * <code>.com.cloudera.labs.envelope.input.translate.IncludedExample included_example = 1;</code>
     */
    public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExampleOrBuilder getIncludedExampleOrBuilder() {
      return getIncludedExample();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (includedExample_ != null) {
        output.writeMessage(1, getIncludedExample());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (includedExample_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getIncludedExample());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample)) {
        return super.equals(obj);
      }
      com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample other = (com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample) obj;

      boolean result = true;
      result = result && (hasIncludedExample() == other.hasIncludedExample());
      if (hasIncludedExample()) {
        result = result && getIncludedExample()
            .equals(other.getIncludedExample());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIncludedExample()) {
        hash = (37 * hash) + INCLUDED_EXAMPLE_FIELD_NUMBER;
        hash = (53 * hash) + getIncludedExample().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.cloudera.labs.envelope.input.translate.MultipleExample}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cloudera.labs.envelope.input.translate.MultipleExample)
        com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.internal_static_com_cloudera_labs_envelope_input_translate_MultipleExample_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.internal_static_com_cloudera_labs_envelope_input_translate_MultipleExample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample.class, com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample.Builder.class);
      }

      // Construct using com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (includedExampleBuilder_ == null) {
          includedExample_ = null;
        } else {
          includedExample_ = null;
          includedExampleBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.internal_static_com_cloudera_labs_envelope_input_translate_MultipleExample_descriptor;
      }

      @java.lang.Override
      public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample getDefaultInstanceForType() {
        return com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample.getDefaultInstance();
      }

      @java.lang.Override
      public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample build() {
        com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample buildPartial() {
        com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample result = new com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample(this);
        if (includedExampleBuilder_ == null) {
          result.includedExample_ = includedExample_;
        } else {
          result.includedExample_ = includedExampleBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample) {
          return mergeFrom((com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample other) {
        if (other == com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample.getDefaultInstance()) return this;
        if (other.hasIncludedExample()) {
          mergeIncludedExample(other.getIncludedExample());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample includedExample_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample, com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.Builder, com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExampleOrBuilder> includedExampleBuilder_;
      /**
       * <code>.com.cloudera.labs.envelope.input.translate.IncludedExample included_example = 1;</code>
       */
      public boolean hasIncludedExample() {
        return includedExampleBuilder_ != null || includedExample_ != null;
      }
      /**
       * <code>.com.cloudera.labs.envelope.input.translate.IncludedExample included_example = 1;</code>
       */
      public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample getIncludedExample() {
        if (includedExampleBuilder_ == null) {
          return includedExample_ == null ? com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.getDefaultInstance() : includedExample_;
        } else {
          return includedExampleBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.cloudera.labs.envelope.input.translate.IncludedExample included_example = 1;</code>
       */
      public Builder setIncludedExample(com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample value) {
        if (includedExampleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          includedExample_ = value;
          onChanged();
        } else {
          includedExampleBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.cloudera.labs.envelope.input.translate.IncludedExample included_example = 1;</code>
       */
      public Builder setIncludedExample(
          com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.Builder builderForValue) {
        if (includedExampleBuilder_ == null) {
          includedExample_ = builderForValue.build();
          onChanged();
        } else {
          includedExampleBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.cloudera.labs.envelope.input.translate.IncludedExample included_example = 1;</code>
       */
      public Builder mergeIncludedExample(com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample value) {
        if (includedExampleBuilder_ == null) {
          if (includedExample_ != null) {
            includedExample_ =
              com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.newBuilder(includedExample_).mergeFrom(value).buildPartial();
          } else {
            includedExample_ = value;
          }
          onChanged();
        } else {
          includedExampleBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.cloudera.labs.envelope.input.translate.IncludedExample included_example = 1;</code>
       */
      public Builder clearIncludedExample() {
        if (includedExampleBuilder_ == null) {
          includedExample_ = null;
          onChanged();
        } else {
          includedExample_ = null;
          includedExampleBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.cloudera.labs.envelope.input.translate.IncludedExample included_example = 1;</code>
       */
      public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.Builder getIncludedExampleBuilder() {
        
        onChanged();
        return getIncludedExampleFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.cloudera.labs.envelope.input.translate.IncludedExample included_example = 1;</code>
       */
      public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExampleOrBuilder getIncludedExampleOrBuilder() {
        if (includedExampleBuilder_ != null) {
          return includedExampleBuilder_.getMessageOrBuilder();
        } else {
          return includedExample_ == null ?
              com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.getDefaultInstance() : includedExample_;
        }
      }
      /**
       * <code>.com.cloudera.labs.envelope.input.translate.IncludedExample included_example = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample, com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.Builder, com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExampleOrBuilder> 
          getIncludedExampleFieldBuilder() {
        if (includedExampleBuilder_ == null) {
          includedExampleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample, com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExample.Builder, com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.IncludedExampleOrBuilder>(
                  getIncludedExample(),
                  getParentForChildren(),
                  isClean());
          includedExample_ = null;
        }
        return includedExampleBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.cloudera.labs.envelope.input.translate.MultipleExample)
    }

    // @@protoc_insertion_point(class_scope:com.cloudera.labs.envelope.input.translate.MultipleExample)
    private static final com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample();
    }

    public static com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultipleExample>
        PARSER = new com.google.protobuf.AbstractParser<MultipleExample>() {
      @java.lang.Override
      public MultipleExample parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MultipleExample(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MultipleExample> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MultipleExample> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cloudera.labs.envelope.input.translate.ProtobufMultipleMessage.MultipleExample getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloudera_labs_envelope_input_translate_OtherExample_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloudera_labs_envelope_input_translate_OtherExample_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloudera_labs_envelope_input_translate_IncludedExample_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloudera_labs_envelope_input_translate_IncludedExample_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloudera_labs_envelope_input_translate_MultipleExample_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloudera_labs_envelope_input_translate_MultipleExample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037protobuf_multiple_message.proto\022*com.c" +
      "loudera.labs.envelope.input.translate\"\035\n" +
      "\014OtherExample\022\r\n\005other\030\001 \001(\t\"#\n\017Included" +
      "Example\022\020\n\010included\030\001 \001(\t\"h\n\017MultipleExa" +
      "mple\022U\n\020included_example\030\001 \001(\0132;.com.clo" +
      "udera.labs.envelope.input.translate.Incl" +
      "udedExampleb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_cloudera_labs_envelope_input_translate_OtherExample_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cloudera_labs_envelope_input_translate_OtherExample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloudera_labs_envelope_input_translate_OtherExample_descriptor,
        new java.lang.String[] { "Other", });
    internal_static_com_cloudera_labs_envelope_input_translate_IncludedExample_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_cloudera_labs_envelope_input_translate_IncludedExample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloudera_labs_envelope_input_translate_IncludedExample_descriptor,
        new java.lang.String[] { "Included", });
    internal_static_com_cloudera_labs_envelope_input_translate_MultipleExample_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_cloudera_labs_envelope_input_translate_MultipleExample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloudera_labs_envelope_input_translate_MultipleExample_descriptor,
        new java.lang.String[] { "IncludedExample", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
