= Contributing to Envelope

*tl;dr*

_Hack:_ Fork the repo, PR against the `develop` branch.

_Build:_ Pull library from Maven repo, submit Spark job

== Hacking Envelope

Envelope is designed for extensibility, so new components are expected and encouraged. Most often, a developer adds a
new function simply by implementing a core interface, constructing the code as a jar file, and referencing the function
in the configuration directly.

For work on the framework itself, we follow a mix of two workflows,
https://www.atlassian.com/git/tutorials/comparing-workflows#gitflow-workflow[Gitflow] and
https://www.atlassian.com/git/tutorials/comparing-workflows#forking-workflow[Forking].

The central repository implements many of the concepts in Gitflow. For example, Envelope has two main branches, `master`
and `develop`, the former is designed for releases, the latter for stable development. Hotfixes, etc. follow the
guidelines set down in the Gitflow documentation.

Development work, however, does not use the branches defined in Gitflow (we might under certain circumstances, but have
not to date). Instead, we use the Forking workflow, that is a developer creates a branch against `develop` in their own,
forked repository of Envelope and issues a pull request (PR) from that branch to the `develop`  branch on the central
repository.

=== Pull Requests

Developers should prefix their PRs with the associated JIRA issue, if one is available. For example, "[ENV-74] Remove
requirement for application name." A PR is reviewed via GitHub's UI, and our convention is that the PR submitter cannot
be the committer as well. Committed PRs should use "squash and merge" in order to streamline the Git history.

Lastly, commits should be short and descriptive, using present tense verbs, i.e. "Remove requirement for application
name". Why, you ask? It just reads better, don't you think?

=== Unit Tests

All code should include unit tests whenever possible. We rely on JUnit and JMock. Currently, we do not have full
integration tests, though this functionality is on the roadmap.

=== Documentation

Envelope documentation should be written in http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc] and
use the `.adoc` file extension.  AsciiDoc allows us to publish documentation in many forms and use a number of plugins,
like graphing, etc.  It also is supported natively by GitHub and looks and feels a lot like Markdown.

All public APIs should have Javadocs.

== Building with Envelope

Envelope is designed with configuration in mind, so using Envelope can be as easy as tweaking a configuration file
and submitted a Spark job.

The pieces to an Envelope application are pretty simple:

. Configuration file (see link:configurations.adoc[Configurations] for details)
. Supporting JARs, like a custom Deriver
. Supporting assets, like Morphline configurations or CSV files
. Envelope JAR

At minimum, the application needs the configuration file and the Envelope JAR.